GET http://localhost:3000/assets


###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "Asset3",
  "symbol": "A3",
  "price": 100
}

###
GET http://localhost:3000/wallets

###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet3"
}

###
GET http://localhost:3000/wallets/wallet1/assets

###
POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 10
}